apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: retail-app
  labels:
    app: catalog
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: "mysql"
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: "PLACEHOLDER_RDS_ENDPOINT:3306"
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: "catalogdb"
  RETAIL_CATALOG_PERSISTENCE_USER: "dbadmin"
