#!/usr/bin/env bash
# terraform/apply.sh — terraform init + apply, save outputs, generate grading.json
# Called by main.sh. Do not run directly.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../common.sh"

log_info "Initialising Terraform..."
terraform -chdir="$TERRAFORM_DIR" init -reconfigure

log_info "Applying Terraform (EKS takes ~15-20 minutes)..."
terraform -chdir="$TERRAFORM_DIR" apply -auto-approve


log_info "Saving outputs to $TF_OUTPUTS_FILE ..."

CLUSTER_NAME=$(get_tf_output cluster_name)
CLUSTER_ENDPOINT=$(get_tf_output cluster_endpoint)
REGION=$(get_tf_output region)
VPC_ID=$(get_tf_output vpc_id)
ASSETS_BUCKET=$(get_tf_output assets_bucket_name)
CART_IRSA_ARN=$(get_tf_output cart_irsa_role_arn)
GITHUB_ROLE_ARN=$(get_tf_output github_oidc_role_arn)

cat > "$TF_OUTPUTS_FILE" <<EOF
# Auto-generated by terraform/apply.sh — do not commit this file
CLUSTER_NAME="$CLUSTER_NAME"
CLUSTER_ENDPOINT="$CLUSTER_ENDPOINT"
REGION="$REGION"
VPC_ID="$VPC_ID"
ASSETS_BUCKET="$ASSETS_BUCKET"
CART_IRSA_ARN="$CART_IRSA_ARN"
GITHUB_ROLE_ARN="$GITHUB_ROLE_ARN"
EOF


log_info "Generating grading.json..."
terraform -chdir="$TERRAFORM_DIR" output -json > "$REPO_DIR/grading.json"
log_success "grading.json written — commit and push this file"

log_success "Terraform apply complete."
echo ""
echo "  Cluster      : $CLUSTER_NAME"
echo "  Endpoint     : $CLUSTER_ENDPOINT"
echo "  Region       : $REGION"
echo "  VPC          : $VPC_ID"
echo "  Assets bucket: $ASSETS_BUCKET"
echo "  GitHub role  : $GITHUB_ROLE_ARN"
echo ""
log_warn "ACTION REQUIRED: Add the GitHub role ARN above as secret AWS_ROLE_ARN in your repo"
log_info "Next: ./scripts/k8s/main.sh all"
