apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: retail-app
  labels:
    app: ui
data:
  RETAIL_UI_CATALOG_URL: "http://catalog:8080"
  RETAIL_UI_ORDERS_URL: "http://orders:8080"
  RETAIL_UI_CHECKOUT_URL: "http://checkout:8080"
  RETAIL_UI_CART_URL: "http://cart:8080"
