#!/usr/bin/env bash

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Absolute path to the scripts directory (works regardless of where scripts are called from)
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
TERRAFORM_DIR="$REPO_DIR/terraform"
HELM_DIR="$REPO_DIR/helm/retail-store"
HELM_VALUES="$REPO_DIR/helm/values.yaml"
HELM_VALUES_GENERATED="$REPO_DIR/helm/values.generated.yaml"
TF_OUTPUTS_FILE="$SCRIPTS_DIR/.tf-outputs"


log_info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_success() { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }


check_terraform_deps() {
  local missing=0
  for cmd in terraform; do
    if ! command -v "$cmd" &>/dev/null; then
      log_error "Required tool not found: $cmd"
      missing=1
    fi
  done
  if [[ $missing -eq 1 ]]; then
    log_error "Install missing tools and re-run."
    exit 1
  fi
  log_success "All required tools found (terraform)"
}

check_k8s_deps() {
  local missing=0
  for cmd in aws kubectl jq helm; do
    if ! command -v "$cmd" &>/dev/null; then
      log_error "Required tool not found: $cmd"
      missing=1
    fi
  done
  if [[ $missing -eq 1 ]]; then
    log_error "Install missing tools and re-run."
    exit 1
  fi
  log_success "All required tools found (aws, kubectl, jq, helm)"
}


get_secret_password() {
  local secret_id="$1"
  local region="$2"
  aws secretsmanager get-secret-value \
    --region "$region" \
    --secret-id "$secret_id" \
    --query SecretString \
    --output text | jq -r '.password'
}


# Terraform RDS endpoint output is host:port; append port only when missing.
normalize_db_endpoint() {
  local host="$1"
  local default_port="$2"
  if [[ "$host" == *:* ]]; then
    echo "$host"
  else
    echo "${host}:${default_port}"
  fi
}


generate_helm_values() {
  local mysql_host postgres_host mysql_endpoint postgres_endpoint
  local cart_irsa region mysql_password postgres_password

  mysql_host=$(get_tf_output mysql_endpoint)
  postgres_host=$(get_tf_output postgres_endpoint)
  cart_irsa=$(get_tf_output cart_irsa_role_arn)
  region=$(get_tf_output region)

  if [[ -z "$mysql_host" || -z "$postgres_host" ]]; then
    log_error "RDS endpoints not found in Terraform state."
    log_error "Run: ./scripts/terraform/main.sh apply"
    exit 1
  fi

  if [[ -z "$cart_irsa" ]]; then
    log_error "cart IRSA role ARN not found in Terraform state."
    log_error "Run: ./scripts/terraform/main.sh apply"
    exit 1
  fi

  mysql_endpoint=$(normalize_db_endpoint "$mysql_host" 3306)
  postgres_endpoint=$(normalize_db_endpoint "$postgres_host" 5432)

  log_info "Fetching RDS passwords from Secrets Manager..."
  mysql_password=$(get_secret_password "project-bedrock/rds/mysql" "$region")
  postgres_password=$(get_secret_password "project-bedrock/rds/postgres" "$region")

  cat > "$HELM_VALUES_GENERATED" <<EOF
# Auto-generated by scripts — do not commit this file
catalog:
  app:
    persistence:
      endpoint: "${mysql_endpoint}"
      secret:
        password: "${mysql_password}"

orders:
  app:
    persistence:
      endpoint: "${postgres_endpoint}"
      secret:
        password: "${postgres_password}"

cart:
  awsRegion: "${region}"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${cart_irsa}"
EOF

  log_success "Generated $HELM_VALUES_GENERATED"
  log_info "  catalog endpoint: ${mysql_endpoint}"
  log_info "  orders endpoint:  ${postgres_endpoint}"
}


get_tf_output() {
  local key="$1"
  terraform -chdir="$TERRAFORM_DIR" output -raw "$key" 2>/dev/null || true
}


load_tf_outputs() {
  if [[ ! -f "$TF_OUTPUTS_FILE" ]]; then
    log_error ".tf-outputs not found. Run terraform/apply.sh first."
    exit 1
  fi
  # shellcheck source=/dev/null
  source "$TF_OUTPUTS_FILE"
  log_info "Loaded terraform outputs from $TF_OUTPUTS_FILE"
}
