#!/usr/bin/env bash
# tf-apply.sh — run terraform init + apply and save outputs
# Usage: ./scripts/tf-apply.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

check_deps

log_info "Initialising Terraform..."
terraform -chdir="$TERRAFORM_DIR" init -reconfigure

log_info "Applying Terraform (this can take 15-20 minutes for EKS)..."
terraform -chdir="$TERRAFORM_DIR" apply -auto-approve

# ─── Save outputs for use by k8s scripts ────────────────────────────────────

log_info "Saving Terraform outputs to $TF_OUTPUTS_FILE ..."

CLUSTER_NAME=$(get_tf_output cluster_name)
CLUSTER_ENDPOINT=$(get_tf_output cluster_endpoint)
REGION=$(get_tf_output region)
VPC_ID=$(get_tf_output vpc_id)
ASSETS_BUCKET=$(get_tf_output assets_bucket_name)
CART_IRSA_ARN=$(get_tf_output cart_irsa_role_arn)

cat > "$TF_OUTPUTS_FILE" <<EOF
# Auto-generated by tf-apply.sh — do not commit this file
CLUSTER_NAME="$CLUSTER_NAME"
CLUSTER_ENDPOINT="$CLUSTER_ENDPOINT"
REGION="$REGION"
VPC_ID="$VPC_ID"
ASSETS_BUCKET="$ASSETS_BUCKET"
CART_IRSA_ARN="$CART_IRSA_ARN"
EOF

log_success "Terraform apply complete. Outputs:"
echo ""
echo "  Cluster name     : $CLUSTER_NAME"
echo "  Cluster endpoint : $CLUSTER_ENDPOINT"
echo "  Region           : $REGION"
echo "  VPC ID           : $VPC_ID"
echo "  Assets bucket    : $ASSETS_BUCKET"
echo "  Cart IRSA ARN    : $CART_IRSA_ARN"
echo ""
log_info "Next step: ./scripts/k8s-configure.sh"
