apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
  namespace: retail-app
  labels:
    app: cart
data:
  RETAIL_CART_PERSISTENCE_PROVIDER: "dynamodb"
  RETAIL_CART_DYNAMODB_TABLE_NAME: "project-bedrock-cart"
  AWS_REGION: "us-east-1"
